UPDATE_MONODOMAIN_STATIC_DEPS="alg config_helpers utils"

if [ -n "$CUDA_FOUND" ]; then
  UPDATE_MONODOMAIN_STATIC_DEPS="$UPDATE_MONODOMAIN_DEPS"
  UPDATE_MONODOMAIN_DYNAMIC_DEPS="cudart"
fi

if [ -n "$SYCL_FOUND" ]; then
  UPDATE_MONODOMAIN_STATIC_DEPS="$UPDATE_MONODOMAIN_DEPS"
  #UPDATE_MONODOMAIN_STATIC_DEPS="$SYCL_LIBRARY_PATH"
  UPDATE_MONODOMAIN_DYNAMIC_DEPS=""
fi

COMPILE_SHARED_LIB "default_update_monodomain" "update_monodomain.cpp" "" "$UPDATE_MONODOMAIN_STATIC_DEPS"  "$UPDATE_MONODOMAIN_DYNAMIC_DEPS" "$CUDA_LIBRARY_PATH" "" "$CUDA_FOUND" "$SYCL_FOUND"