GPU_UTILS_SOURCE_FILES="gpu_utils.c"
GPU_UTILS_HEADER_FILES="gpu_utils.h"
SYCL_UTILS_SOURCE_FILES="sycl_utils.c"
SYCL_UTILS_HEADER_FILES="sycl_utils.h"

if [ -n "$CUDA_FOUND" ]; then
    GPU_UTILS_EXTRA_LIB_PATH=$CUDA_LIBRARY_PATH
    GPU_UTILS_DYNAMIC_LIBS="c cudart"
    GPU_UTILS_SOURCE_FILES="$GPU_UTILS_SOURCE_FILES gpu_utils.cu"
    COMPILE_SHARED_LIB "gpu_utils" "$GPU_UTILS_SOURCE_FILES" "$GPU_UTILS_HEADER_FILES" "" "$GPU_UTILS_DYNAMIC_LIBS" "$GPU_UTILS_EXTRA_LIB_PATH" "" "$CUDA_FOUND"
fi

if [ -n "$SYCL_FOUND" ]; then
    SYCL_UTILS_EXTRA_LIB_PATH=$SYCL_LIBRARY_PATH
    SYCL_UTILS_DYNAMIC_LIBS="c"
    SYCL_UTILS_SOURCE_FILES="$SYCL_UTILS_SOURCE_FILES sycl_utils.cpp"
    COMPILE_SHARED_LIB "sycl_utils" "$SYCL_UTILS_SOURCE_FILES" "$SYCL_UTILS_HEADER_FILES" "" "$SYCL_UTILS_DYNAMIC_LIBS" "$SYCL_UTILS_EXTRA_LIB_PATH" "" "$SYCL_FOUND"
fi

#COMPILE_STATIC_LIB "gpu_utils" "$GPU_UTILS_SOURCE_FILES" "$GPU_UTILS_HEADER_FILES"
