MONODOMAIN_SOURCE_FILES="monodomain_solver.cpp"
MONODOMAIN_HEADER_FILES="monodomain_solver.h"

COMPILE_STATIC_LIB "monodomain" "$MONODOMAIN_SOURCE_FILES" "$MONODOMAIN_HEADER_FILES" "" "$CUDA_FOUND" "$SYCL_FOUND"
